<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Icon\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Icon\user.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.6.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.6.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Icon\user.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>

    <Resource Include="Assets\Images\logo-text.png" />
    <Resource Include="Assets\Images\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\fonts\ARIAL.TTF">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\fonts\ARIALBD.TTF">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Icon\logo.ico" />
    <Content Include="Assets\Images\logo.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
   </ItemGroup>

</Project>
