INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hydrocortisone Cream 1%', N'Hydrocortisone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Betamethasone Dipropionate 0.05%', N'Betamethasone Dipropionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clobetasol Propionate 0.05%', N'Clobetasol Propionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Triamcinolone Acetonide 0.1%', N'Triamcinolone Acetonide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Mometasone Furoate 0.1%', N'Mometasone Furoate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.03%', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.1%', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Pimecrolimus Cream 1%', N'Pimecrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.1%', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.3%', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.025%', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.05%', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.1%', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 2.5%', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 5%', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 10%', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin Gel 1%', N'Clindamycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin + Benzoyl Peroxide', N'Clindamycin + Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Erythromycin Gel 2%', N'Erythromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 15%', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 20%', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Cream 2%', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Shampoo 2%', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clotrimazole Cream 1%', N'Clotrimazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Miconazole Cream 2%', N'Miconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Cream 1%', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Tablet 250mg', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Fluconazole 150mg', N'Fluconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Itraconazole 100mg', N'Itraconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Cream 5%', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Tablet 400mg', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Valacyclovir 500mg', N'Valacyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Dapsone Gel 7.5%', N'Dapsone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 10mg', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 20mg', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 30mg', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 40mg', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Salicylic Acid 2%', N'Salicylic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 10%', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 20%', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 40%', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hyaluronic Acid Serum', N'Hyaluronic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Niacinamide Serum 10%', N'Niacinamide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azithromycin 250mg', N'Azithromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Cefalexin 500mg', N'Cefalexin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Prednisolone 5mg', N'Prednisolone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Cream 0.77%', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Shampoo 1%', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 0.75%', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 1%', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hydrocortisone Cream 1% - Variant 1', N'Hydrocortisone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 1', N'Betamethasone Dipropionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clobetasol Propionate 0.05% - Variant 1', N'Clobetasol Propionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 1', N'Triamcinolone Acetonide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Mometasone Furoate 0.1% - Variant 1', N'Mometasone Furoate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.03% - Variant 1', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.1% - Variant 1', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Pimecrolimus Cream 1% - Variant 1', N'Pimecrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.1% - Variant 1', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.3% - Variant 1', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.025% - Variant 1', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.05% - Variant 1', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.1% - Variant 1', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 2.5% - Variant 1', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 5% - Variant 1', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 10% - Variant 1', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin Gel 1% - Variant 1', N'Clindamycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 1', N'Clindamycin + Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Erythromycin Gel 2% - Variant 1', N'Erythromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 15% - Variant 1', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 20% - Variant 1', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Cream 2% - Variant 1', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Shampoo 2% - Variant 1', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clotrimazole Cream 1% - Variant 1', N'Clotrimazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Miconazole Cream 2% - Variant 1', N'Miconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Cream 1% - Variant 1', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Tablet 250mg - Variant 1', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Fluconazole 150mg - Variant 1', N'Fluconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Itraconazole 100mg - Variant 1', N'Itraconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Cream 5% - Variant 1', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Tablet 400mg - Variant 1', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Valacyclovir 500mg - Variant 1', N'Valacyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Dapsone Gel 7.5% - Variant 1', N'Dapsone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 10mg - Variant 1', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 20mg - Variant 1', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 30mg - Variant 1', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 40mg - Variant 1', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Salicylic Acid 2% - Variant 1', N'Salicylic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 10% - Variant 1', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 20% - Variant 1', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 40% - Variant 1', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hyaluronic Acid Serum - Variant 1', N'Hyaluronic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Niacinamide Serum 10% - Variant 1', N'Niacinamide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azithromycin 250mg - Variant 1', N'Azithromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Cefalexin 500mg - Variant 1', N'Cefalexin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Prednisolone 5mg - Variant 1', N'Prednisolone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Cream 0.77% - Variant 1', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Shampoo 1% - Variant 1', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 0.75% - Variant 1', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 1% - Variant 1', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hydrocortisone Cream 1% - Variant 2', N'Hydrocortisone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 2', N'Betamethasone Dipropionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clobetasol Propionate 0.05% - Variant 2', N'Clobetasol Propionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 2', N'Triamcinolone Acetonide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Mometasone Furoate 0.1% - Variant 2', N'Mometasone Furoate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.03% - Variant 2', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.1% - Variant 2', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Pimecrolimus Cream 1% - Variant 2', N'Pimecrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.1% - Variant 2', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.3% - Variant 2', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.025% - Variant 2', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.05% - Variant 2', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.1% - Variant 2', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 2.5% - Variant 2', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 5% - Variant 2', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 10% - Variant 2', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin Gel 1% - Variant 2', N'Clindamycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 2', N'Clindamycin + Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Erythromycin Gel 2% - Variant 2', N'Erythromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 15% - Variant 2', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 20% - Variant 2', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Cream 2% - Variant 2', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Shampoo 2% - Variant 2', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clotrimazole Cream 1% - Variant 2', N'Clotrimazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Miconazole Cream 2% - Variant 2', N'Miconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Cream 1% - Variant 2', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Tablet 250mg - Variant 2', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Fluconazole 150mg - Variant 2', N'Fluconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Itraconazole 100mg - Variant 2', N'Itraconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Cream 5% - Variant 2', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Tablet 400mg - Variant 2', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Valacyclovir 500mg - Variant 2', N'Valacyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Dapsone Gel 7.5% - Variant 2', N'Dapsone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 10mg - Variant 2', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 20mg - Variant 2', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 30mg - Variant 2', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 40mg - Variant 2', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Salicylic Acid 2% - Variant 2', N'Salicylic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 10% - Variant 2', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 20% - Variant 2', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 40% - Variant 2', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hyaluronic Acid Serum - Variant 2', N'Hyaluronic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Niacinamide Serum 10% - Variant 2', N'Niacinamide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azithromycin 250mg - Variant 2', N'Azithromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Cefalexin 500mg - Variant 2', N'Cefalexin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Prednisolone 5mg - Variant 2', N'Prednisolone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Cream 0.77% - Variant 2', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Shampoo 1% - Variant 2', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 0.75% - Variant 2', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 1% - Variant 2', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hydrocortisone Cream 1% - Variant 3', N'Hydrocortisone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 3', N'Betamethasone Dipropionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clobetasol Propionate 0.05% - Variant 3', N'Clobetasol Propionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 3', N'Triamcinolone Acetonide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Mometasone Furoate 0.1% - Variant 3', N'Mometasone Furoate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.03% - Variant 3', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.1% - Variant 3', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Pimecrolimus Cream 1% - Variant 3', N'Pimecrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.1% - Variant 3', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.3% - Variant 3', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.025% - Variant 3', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.05% - Variant 3', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.1% - Variant 3', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 2.5% - Variant 3', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 5% - Variant 3', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 10% - Variant 3', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin Gel 1% - Variant 3', N'Clindamycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 3', N'Clindamycin + Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Erythromycin Gel 2% - Variant 3', N'Erythromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 15% - Variant 3', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 20% - Variant 3', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Cream 2% - Variant 3', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Shampoo 2% - Variant 3', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clotrimazole Cream 1% - Variant 3', N'Clotrimazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Miconazole Cream 2% - Variant 3', N'Miconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Cream 1% - Variant 3', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Tablet 250mg - Variant 3', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Fluconazole 150mg - Variant 3', N'Fluconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Itraconazole 100mg - Variant 3', N'Itraconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Cream 5% - Variant 3', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Tablet 400mg - Variant 3', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Valacyclovir 500mg - Variant 3', N'Valacyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Dapsone Gel 7.5% - Variant 3', N'Dapsone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 10mg - Variant 3', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 20mg - Variant 3', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 30mg - Variant 3', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 40mg - Variant 3', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Salicylic Acid 2% - Variant 3', N'Salicylic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 10% - Variant 3', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 20% - Variant 3', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 40% - Variant 3', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hyaluronic Acid Serum - Variant 3', N'Hyaluronic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Niacinamide Serum 10% - Variant 3', N'Niacinamide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azithromycin 250mg - Variant 3', N'Azithromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Cefalexin 500mg - Variant 3', N'Cefalexin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Prednisolone 5mg - Variant 3', N'Prednisolone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Cream 0.77% - Variant 3', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Shampoo 1% - Variant 3', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 0.75% - Variant 3', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 1% - Variant 3', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hydrocortisone Cream 1% - Variant 4', N'Hydrocortisone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 4', N'Betamethasone Dipropionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clobetasol Propionate 0.05% - Variant 4', N'Clobetasol Propionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 4', N'Triamcinolone Acetonide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Mometasone Furoate 0.1% - Variant 4', N'Mometasone Furoate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.03% - Variant 4', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.1% - Variant 4', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Pimecrolimus Cream 1% - Variant 4', N'Pimecrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.1% - Variant 4', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.3% - Variant 4', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.025% - Variant 4', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.05% - Variant 4', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.1% - Variant 4', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 2.5% - Variant 4', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 5% - Variant 4', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 10% - Variant 4', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin Gel 1% - Variant 4', N'Clindamycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 4', N'Clindamycin + Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Erythromycin Gel 2% - Variant 4', N'Erythromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 15% - Variant 4', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 20% - Variant 4', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Cream 2% - Variant 4', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Shampoo 2% - Variant 4', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clotrimazole Cream 1% - Variant 4', N'Clotrimazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Miconazole Cream 2% - Variant 4', N'Miconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Cream 1% - Variant 4', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Tablet 250mg - Variant 4', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Fluconazole 150mg - Variant 4', N'Fluconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Itraconazole 100mg - Variant 4', N'Itraconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Cream 5% - Variant 4', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Tablet 400mg - Variant 4', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Valacyclovir 500mg - Variant 4', N'Valacyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Dapsone Gel 7.5% - Variant 4', N'Dapsone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 10mg - Variant 4', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 20mg - Variant 4', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 30mg - Variant 4', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 40mg - Variant 4', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Salicylic Acid 2% - Variant 4', N'Salicylic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 10% - Variant 4', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 20% - Variant 4', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 40% - Variant 4', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hyaluronic Acid Serum - Variant 4', N'Hyaluronic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Niacinamide Serum 10% - Variant 4', N'Niacinamide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azithromycin 250mg - Variant 4', N'Azithromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Cefalexin 500mg - Variant 4', N'Cefalexin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Prednisolone 5mg - Variant 4', N'Prednisolone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Cream 0.77% - Variant 4', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Shampoo 1% - Variant 4', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 0.75% - Variant 4', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 1% - Variant 4', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hydrocortisone Cream 1% - Variant 5', N'Hydrocortisone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 5', N'Betamethasone Dipropionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clobetasol Propionate 0.05% - Variant 5', N'Clobetasol Propionate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 5', N'Triamcinolone Acetonide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Mometasone Furoate 0.1% - Variant 5', N'Mometasone Furoate');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.03% - Variant 5', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tacrolimus Ointment 0.1% - Variant 5', N'Tacrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Pimecrolimus Cream 1% - Variant 5', N'Pimecrolimus');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.1% - Variant 5', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Adapalene Gel 0.3% - Variant 5', N'Adapalene');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.025% - Variant 5', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.05% - Variant 5', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Tretinoin Cream 0.1% - Variant 5', N'Tretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 2.5% - Variant 5', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 5% - Variant 5', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Benzoyl Peroxide 10% - Variant 5', N'Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin Gel 1% - Variant 5', N'Clindamycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 5', N'Clindamycin + Benzoyl Peroxide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Erythromycin Gel 2% - Variant 5', N'Erythromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 15% - Variant 5', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azelaic Acid 20% - Variant 5', N'Azelaic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Cream 2% - Variant 5', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ketoconazole Shampoo 2% - Variant 5', N'Ketoconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Clotrimazole Cream 1% - Variant 5', N'Clotrimazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Miconazole Cream 2% - Variant 5', N'Miconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Cream 1% - Variant 5', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Terbinafine Tablet 250mg - Variant 5', N'Terbinafine');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Fluconazole 150mg - Variant 5', N'Fluconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Itraconazole 100mg - Variant 5', N'Itraconazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Cream 5% - Variant 5', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Acyclovir Tablet 400mg - Variant 5', N'Acyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Valacyclovir 500mg - Variant 5', N'Valacyclovir');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Dapsone Gel 7.5% - Variant 5', N'Dapsone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 10mg - Variant 5', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 20mg - Variant 5', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 30mg - Variant 5', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Isotretinoin 40mg - Variant 5', N'Isotretinoin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Salicylic Acid 2% - Variant 5', N'Salicylic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 10% - Variant 5', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 20% - Variant 5', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Urea Cream 40% - Variant 5', N'Urea');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Hyaluronic Acid Serum - Variant 5', N'Hyaluronic Acid');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Niacinamide Serum 10% - Variant 5', N'Niacinamide');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Azithromycin 250mg - Variant 5', N'Azithromycin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Cefalexin 500mg - Variant 5', N'Cefalexin');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Prednisolone 5mg - Variant 5', N'Prednisolone');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Cream 0.77% - Variant 5', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Ciclopirox Shampoo 1% - Variant 5', N'Ciclopirox');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 0.75% - Variant 5', N'Metronidazole');
INSERT INTO Thuoc (TenThuoc, HoatChat) VALUES (N'Metronidazole Gel 1% - Variant 5', N'Metronidazole');