INSERT INTO LoaiBenh (TenBenh, TenKhoaHoc, NhomBenh, MoTa, DoPhoBien, MucDoNghiemTrong) VALUES
(N'Viêm da cơ địa', N'Atopic dermatitis', N'Viêm da', N'Bệnh mạn tính gây khô và ngứa da.', N'phổ biến', N'trung bình'),
(N'Viêm da tiếp xúc', N'Contact dermatitis', N'Viêm da', N'Phản ứng viêm khi da tiếp xúc chất kích ứng.', N'phổ biến', N'trung bình'),
(N'Mề đay', N'Urticaria', N'Dị ứng', N'Nổi mẩn đỏ và ngứa đột ngột.', N'phổ biến', N'nhẹ'),
(N'Phù mạch', N'Angioedema', N'Dị ứng', N'Sưng lớp mô sâu dưới da.', N'ít gặp', N'nặng'),
(N'Mụn trứng cá', N'Acne vulgaris', N'Viêm da', N'Tắc nghẽn lỗ chân lông gây mụn.', N'phổ biến', N'nhẹ'),
(N'Viêm nang lông', N'Folliculitis', N'Nhiễm trùng', N'Viêm nhiễm nang lông gây sẩn đỏ.', N'phổ biến', N'nhẹ'),
(N'Chốc lở', N'Impetigo', N'Nhiễm trùng', N'Nhiễm khuẩn da gây mụn mủ và vảy mật ong.', N'phổ biến', N'nhẹ'),
(N'Viêm mô tế bào', N'Cellulitis', N'Nhiễm trùng', N'Nhiễm khuẩn da lan tỏa gây sưng nóng đỏ đau.', N'phổ biến', N'trung bình'),
(N'Zona', N'Herpes zoster', N'Virus', N'Tái hoạt virus gây đau và nổi mụn nước theo dải.', N'phổ biến', N'trung bình'),
(N'Mụn rộp', N'Herpes simplex', N'Virus', N'Mụn nước nhỏ quanh môi hoặc cơ quan sinh dục.', N'phổ biến', N'nhẹ'),
(N'Lang ben', N'Tinea versicolor', N'Nấm', N'Nấm gây thay đổi sắc tố da.', N'phổ biến', N'nhẹ'),
(N'Hắc lào', N'Tinea corporis', N'Nấm', N'Vòng đỏ có viền rõ trên da.', N'phổ biến', N'nhẹ'),
(N'Nấm kẽ chân', N'Tinea pedis', N'Nấm', N'Nấm ở kẽ chân gây bong vảy.', N'phổ biến', N'nhẹ'),
(N'Nấm da đầu', N'Tinea capitis', N'Nấm', N'Nấm làm rụng tóc thành mảng.', N'ít gặp', N'nhẹ'),
(N'Nấm móng', N'Onychomycosis', N'Nấm', N'Nhiễm nấm móng làm đổi màu và dày móng.', N'phổ biến', N'nhẹ'),
(N'Candida da', N'Cutaneous candidiasis', N'Nấm', N'Nấm Candida gây viêm ở vùng ẩm.', N'phổ biến', N'nhẹ'),
(N'Ghẻ', N'Scabies', N'Ký sinh trùng', N'Ký sinh trùng gây ngứa nhiều về đêm.', N'phổ biến', N'nhẹ'),
(N'Mụn cóc', N'Verruca (HPV)', N'Virus', N'Sùi nhỏ thô ráp trên da.', N'phổ biến', N'nhẹ'),
(N'U nang tuyến bã', N'Epidermoid cyst', N'U lành tính', N'Khối u nhỏ chứa chất bã.', N'phổ biến', N'nhẹ'),
(N'U mỡ', N'Lipoma', N'U lành tính', N'Khối mỡ mềm dưới da.', N'phổ biến', N'nhẹ'),
(N'U sừng tiết bã', N'Seborrheic keratosis', N'U lành tính', N'Mảng tăng sừng màu nâu.', N'phổ biến', N'nhẹ'),
(N'Vảy nến', N'Psoriasis', N'Tự miễn', N'Da tăng sinh gây mảng đỏ và vảy trắng.', N'phổ biến', N'trung bình'),
(N'Bạch biến', N'Vitiligo', N'Tự miễn', N'Mất sắc tố tạo vùng da trắng.', N'ít gặp', N'trung bình'),
(N'Lichen phẳng', N'Lichen planus', N'Tự miễn', N'Sẩn tím phẳng gây ngứa.', N'ít gặp', N'trung bình'),
(N'Pemphigus', N'Pemphigus vulgaris', N'Tự miễn', N'Bóng nước lớn dễ vỡ.', N'hiếm', N'nặng'),
(N'Pemphigoid', N'Bullous pemphigoid', N'Tự miễn', N'Bóng nước căng ở người lớn tuổi.', N'ít gặp', N'nặng'),
(N'Lupus da', N'Cutaneous lupus', N'Tự miễn', N'Tổn thương da do rối loạn miễn dịch.', N'ít gặp', N'trung bình'),
(N'Rụng tóc từng mảng', N'Alopecia areata', N'Tự miễn', N'Rụng tóc thành từng mảng tròn.', N'phổ biến', N'nhẹ'),
(N'Trứng cá đỏ', N'Rosacea', N'Viêm da', N'Đỏ mặt kèm giãn mạch.', N'phổ biến', N'nhẹ'),
(N'Mề đay mạn', N'Chronic urticaria', N'Dị ứng', N'Mề đay kéo dài trên 6 tuần.', N'ít gặp', N'nhẹ'),
(N'Ban đỏ đa dạng', N'Erythema multiforme', N'Miễn dịch', N'Tổn thương dạng bia bắn.', N'ít gặp', N'nhẹ'),
(N'Ban đỏ nút', N'Erythema nodosum', N'Miễn dịch', N'Nốt đỏ đau dưới da.', N'ít gặp', N'trung bình'),
(N'Viêm quanh móng', N'Paronychia', N'Nhiễm trùng', N'Nhiễm khuẩn vùng quanh móng.', N'phổ biến', N'nhẹ'),
(N'Rôm sảy', N'Miliaria', N'Viêm da', N'Tắc tuyến mồ hôi gây mụn đỏ nhỏ.', N'phổ biến', N'nhẹ'),
(N'Bệnh phong', N'Leprosy', N'Nhiễm trùng', N'Vi khuẩn gây tổn thương da và dây thần kinh.', N'hiếm', N'trung bình'),
(N'Ung thư da BCC', N'Basal cell carcinoma', N'Ung thư da', N'Ung thư da phát triển chậm.', N'phổ biến', N'nặng'),
(N'Ung thư da SCC', N'Squamous cell carcinoma', N'Ung thư da', N'Ung thư độ ác tính trung bình.', N'phổ biến', N'nặng'),
(N'U hắc tố ác tính', N'Melanoma', N'Ung thư da', N'Ung thư da nguy hiểm nhất.', N'ít gặp', N'nặng'),
(N'U máu trẻ em', N'Infantile hemangioma', N'U lành tính', N'U mạch máu hay gặp ở trẻ.', N'phổ biến', N'nhẹ'),
(N'Viêm da tiết bã', N'Seborrheic dermatitis', N'Viêm da', N'Vảy nhờn vùng mặt và da đầu.', N'phổ biến', N'nhẹ'),
(N'Hidradenitis suppurativa', N'Hidradenitis suppurativa', N'Viêm mạn', N'Tắc viêm tuyến mồ hôi gây ổ áp xe.', N'ít gặp', N'trung bình'),
(N'Granuloma annulare', N'Granuloma annulare', N'Miễn dịch', N'Sẩn vòng lành tính.', N'ít gặp', N'nhẹ'),
(N'Khô da', N'Xerosis', N'Viêm da', N'Da khô gây ngứa và nứt nẻ.', N'phổ biến', N'nhẹ'),
(N'Vảy cá', N'Ichthyosis', N'Di truyền', N'Da dày và bong vảy dạng cá.', N'hiếm', N'trung bình'),
(N'Molluscum contagiosum', N'Molluscum contagiosum', N'Virus', N'Sẩn bóng do virus gây ra.', N'phổ biến', N'nhẹ'),
(N'Nấm bẹn', N'Tinea cruris', N'Nấm', N'Nấm vùng bẹn gây ngứa.', N'phổ biến', N'nhẹ'),
(N'Dày sừng nang lông', N'Keratosis pilaris', N'Tăng sừng', N'Hạt sần nhỏ ở tay và chân.', N'phổ biến', N'nhẹ'),
(N'Kerion', N'Kerion', N'Nấm', N'Nhiễm nấm da đầu gây ổ mủ.', N'ít gặp', N'trung bình'),
(N'Dày sừng ánh sáng', N'Actinic keratosis', N'Tiền ung thư', N'Mảng sừng do ánh nắng kéo dài.', N'phổ biến', N'trung bình'),
(N'Porphyria da', N'Porphyria cutanea tarda', N'Rối loạn chuyển hóa', N'Da nhạy sáng gây phồng rộp.', N'hiếm', N'nặng');
GO
