INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hydrocortisone Cream 1%', N'Hydrocortisone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Betamethasone Dipropionate 0.05%', N'Betamethasone Dipropionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clobetasol Propionate 0.05%', N'Clobetasol Propionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Triamcinolone Acetonide 0.1%', N'Triamcinolone Acetonide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Mometasone Furoate 0.1%', N'Mometasone Furoate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.03%', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.1%', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Pimecrolimus Cream 1%', N'Pimecrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.1%', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.3%', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.025%', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.05%', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.1%', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 2.5%', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 5%', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 10%', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin Gel 1%', N'Clindamycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin + Benzoyl Peroxide', N'Clindamycin + Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Erythromycin Gel 2%', N'Erythromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 15%', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 20%', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Cream 2%', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Shampoo 2%', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clotrimazole Cream 1%', N'Clotrimazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Miconazole Cream 2%', N'Miconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Cream 1%', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Tablet 250mg', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Fluconazole 150mg', N'Fluconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Itraconazole 100mg', N'Itraconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Cream 5%', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Tablet 400mg', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Valacyclovir 500mg', N'Valacyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Dapsone Gel 7.5%', N'Dapsone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 10mg', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 20mg', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 30mg', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 40mg', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Salicylic Acid 2%', N'Salicylic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 10%', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 20%', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 40%', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hyaluronic Acid Serum', N'Hyaluronic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Niacinamide Serum 10%', N'Niacinamide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azithromycin 250mg', N'Azithromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Cefalexin 500mg', N'Cefalexin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Prednisolone 5mg', N'Prednisolone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Cream 0.77%', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Shampoo 1%', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 0.75%', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 1%', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hydrocortisone Cream 1% - Variant 1', N'Hydrocortisone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 1', N'Betamethasone Dipropionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clobetasol Propionate 0.05% - Variant 1', N'Clobetasol Propionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 1', N'Triamcinolone Acetonide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Mometasone Furoate 0.1% - Variant 1', N'Mometasone Furoate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.03% - Variant 1', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.1% - Variant 1', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Pimecrolimus Cream 1% - Variant 1', N'Pimecrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.1% - Variant 1', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.3% - Variant 1', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.025% - Variant 1', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.05% - Variant 1', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.1% - Variant 1', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 2.5% - Variant 1', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 5% - Variant 1', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 10% - Variant 1', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin Gel 1% - Variant 1', N'Clindamycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 1', N'Clindamycin + Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Erythromycin Gel 2% - Variant 1', N'Erythromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 15% - Variant 1', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 20% - Variant 1', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Cream 2% - Variant 1', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Shampoo 2% - Variant 1', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clotrimazole Cream 1% - Variant 1', N'Clotrimazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Miconazole Cream 2% - Variant 1', N'Miconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Cream 1% - Variant 1', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Tablet 250mg - Variant 1', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Fluconazole 150mg - Variant 1', N'Fluconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Itraconazole 100mg - Variant 1', N'Itraconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Cream 5% - Variant 1', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Tablet 400mg - Variant 1', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Valacyclovir 500mg - Variant 1', N'Valacyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Dapsone Gel 7.5% - Variant 1', N'Dapsone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 10mg - Variant 1', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 20mg - Variant 1', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 30mg - Variant 1', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 40mg - Variant 1', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Salicylic Acid 2% - Variant 1', N'Salicylic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 10% - Variant 1', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 20% - Variant 1', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 40% - Variant 1', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hyaluronic Acid Serum - Variant 1', N'Hyaluronic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Niacinamide Serum 10% - Variant 1', N'Niacinamide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azithromycin 250mg - Variant 1', N'Azithromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Cefalexin 500mg - Variant 1', N'Cefalexin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Prednisolone 5mg - Variant 1', N'Prednisolone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Cream 0.77% - Variant 1', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Shampoo 1% - Variant 1', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 0.75% - Variant 1', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 1% - Variant 1', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hydrocortisone Cream 1% - Variant 2', N'Hydrocortisone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 2', N'Betamethasone Dipropionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clobetasol Propionate 0.05% - Variant 2', N'Clobetasol Propionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 2', N'Triamcinolone Acetonide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Mometasone Furoate 0.1% - Variant 2', N'Mometasone Furoate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.03% - Variant 2', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.1% - Variant 2', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Pimecrolimus Cream 1% - Variant 2', N'Pimecrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.1% - Variant 2', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.3% - Variant 2', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.025% - Variant 2', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.05% - Variant 2', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.1% - Variant 2', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 2.5% - Variant 2', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 5% - Variant 2', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 10% - Variant 2', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin Gel 1% - Variant 2', N'Clindamycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 2', N'Clindamycin + Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Erythromycin Gel 2% - Variant 2', N'Erythromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 15% - Variant 2', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 20% - Variant 2', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Cream 2% - Variant 2', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Shampoo 2% - Variant 2', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clotrimazole Cream 1% - Variant 2', N'Clotrimazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Miconazole Cream 2% - Variant 2', N'Miconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Cream 1% - Variant 2', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Tablet 250mg - Variant 2', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Fluconazole 150mg - Variant 2', N'Fluconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Itraconazole 100mg - Variant 2', N'Itraconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Cream 5% - Variant 2', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Tablet 400mg - Variant 2', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Valacyclovir 500mg - Variant 2', N'Valacyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Dapsone Gel 7.5% - Variant 2', N'Dapsone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 10mg - Variant 2', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 20mg - Variant 2', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 30mg - Variant 2', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 40mg - Variant 2', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Salicylic Acid 2% - Variant 2', N'Salicylic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 10% - Variant 2', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 20% - Variant 2', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 40% - Variant 2', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hyaluronic Acid Serum - Variant 2', N'Hyaluronic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Niacinamide Serum 10% - Variant 2', N'Niacinamide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azithromycin 250mg - Variant 2', N'Azithromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Cefalexin 500mg - Variant 2', N'Cefalexin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Prednisolone 5mg - Variant 2', N'Prednisolone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Cream 0.77% - Variant 2', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Shampoo 1% - Variant 2', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 0.75% - Variant 2', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 1% - Variant 2', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hydrocortisone Cream 1% - Variant 3', N'Hydrocortisone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 3', N'Betamethasone Dipropionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clobetasol Propionate 0.05% - Variant 3', N'Clobetasol Propionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 3', N'Triamcinolone Acetonide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Mometasone Furoate 0.1% - Variant 3', N'Mometasone Furoate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.03% - Variant 3', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.1% - Variant 3', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Pimecrolimus Cream 1% - Variant 3', N'Pimecrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.1% - Variant 3', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.3% - Variant 3', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.025% - Variant 3', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.05% - Variant 3', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.1% - Variant 3', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 2.5% - Variant 3', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 5% - Variant 3', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 10% - Variant 3', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin Gel 1% - Variant 3', N'Clindamycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 3', N'Clindamycin + Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Erythromycin Gel 2% - Variant 3', N'Erythromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 15% - Variant 3', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 20% - Variant 3', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Cream 2% - Variant 3', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Shampoo 2% - Variant 3', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clotrimazole Cream 1% - Variant 3', N'Clotrimazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Miconazole Cream 2% - Variant 3', N'Miconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Cream 1% - Variant 3', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Tablet 250mg - Variant 3', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Fluconazole 150mg - Variant 3', N'Fluconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Itraconazole 100mg - Variant 3', N'Itraconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Cream 5% - Variant 3', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Tablet 400mg - Variant 3', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Valacyclovir 500mg - Variant 3', N'Valacyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Dapsone Gel 7.5% - Variant 3', N'Dapsone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 10mg - Variant 3', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 20mg - Variant 3', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 30mg - Variant 3', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 40mg - Variant 3', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Salicylic Acid 2% - Variant 3', N'Salicylic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 10% - Variant 3', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 20% - Variant 3', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 40% - Variant 3', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hyaluronic Acid Serum - Variant 3', N'Hyaluronic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Niacinamide Serum 10% - Variant 3', N'Niacinamide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azithromycin 250mg - Variant 3', N'Azithromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Cefalexin 500mg - Variant 3', N'Cefalexin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Prednisolone 5mg - Variant 3', N'Prednisolone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Cream 0.77% - Variant 3', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Shampoo 1% - Variant 3', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 0.75% - Variant 3', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 1% - Variant 3', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hydrocortisone Cream 1% - Variant 4', N'Hydrocortisone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 4', N'Betamethasone Dipropionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clobetasol Propionate 0.05% - Variant 4', N'Clobetasol Propionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 4', N'Triamcinolone Acetonide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Mometasone Furoate 0.1% - Variant 4', N'Mometasone Furoate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.03% - Variant 4', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.1% - Variant 4', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Pimecrolimus Cream 1% - Variant 4', N'Pimecrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.1% - Variant 4', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.3% - Variant 4', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.025% - Variant 4', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.05% - Variant 4', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.1% - Variant 4', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 2.5% - Variant 4', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 5% - Variant 4', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 10% - Variant 4', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin Gel 1% - Variant 4', N'Clindamycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 4', N'Clindamycin + Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Erythromycin Gel 2% - Variant 4', N'Erythromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 15% - Variant 4', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 20% - Variant 4', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Cream 2% - Variant 4', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Shampoo 2% - Variant 4', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clotrimazole Cream 1% - Variant 4', N'Clotrimazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Miconazole Cream 2% - Variant 4', N'Miconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Cream 1% - Variant 4', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Tablet 250mg - Variant 4', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Fluconazole 150mg - Variant 4', N'Fluconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Itraconazole 100mg - Variant 4', N'Itraconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Cream 5% - Variant 4', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Tablet 400mg - Variant 4', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Valacyclovir 500mg - Variant 4', N'Valacyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Dapsone Gel 7.5% - Variant 4', N'Dapsone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 10mg - Variant 4', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 20mg - Variant 4', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 30mg - Variant 4', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 40mg - Variant 4', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Salicylic Acid 2% - Variant 4', N'Salicylic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 10% - Variant 4', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 20% - Variant 4', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 40% - Variant 4', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hyaluronic Acid Serum - Variant 4', N'Hyaluronic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Niacinamide Serum 10% - Variant 4', N'Niacinamide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azithromycin 250mg - Variant 4', N'Azithromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Cefalexin 500mg - Variant 4', N'Cefalexin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Prednisolone 5mg - Variant 4', N'Prednisolone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Cream 0.77% - Variant 4', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Shampoo 1% - Variant 4', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 0.75% - Variant 4', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 1% - Variant 4', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hydrocortisone Cream 1% - Variant 5', N'Hydrocortisone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Betamethasone Dipropionate 0.05% - Variant 5', N'Betamethasone Dipropionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clobetasol Propionate 0.05% - Variant 5', N'Clobetasol Propionate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Triamcinolone Acetonide 0.1% - Variant 5', N'Triamcinolone Acetonide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Mometasone Furoate 0.1% - Variant 5', N'Mometasone Furoate', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.03% - Variant 5', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tacrolimus Ointment 0.1% - Variant 5', N'Tacrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Pimecrolimus Cream 1% - Variant 5', N'Pimecrolimus', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.1% - Variant 5', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Adapalene Gel 0.3% - Variant 5', N'Adapalene', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.025% - Variant 5', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.05% - Variant 5', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Tretinoin Cream 0.1% - Variant 5', N'Tretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 2.5% - Variant 5', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 5% - Variant 5', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Benzoyl Peroxide 10% - Variant 5', N'Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin Gel 1% - Variant 5', N'Clindamycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clindamycin + Benzoyl Peroxide - Variant 5', N'Clindamycin + Benzoyl Peroxide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Erythromycin Gel 2% - Variant 5', N'Erythromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 15% - Variant 5', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azelaic Acid 20% - Variant 5', N'Azelaic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Cream 2% - Variant 5', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ketoconazole Shampoo 2% - Variant 5', N'Ketoconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Clotrimazole Cream 1% - Variant 5', N'Clotrimazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Miconazole Cream 2% - Variant 5', N'Miconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Cream 1% - Variant 5', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Terbinafine Tablet 250mg - Variant 5', N'Terbinafine', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Fluconazole 150mg - Variant 5', N'Fluconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Itraconazole 100mg - Variant 5', N'Itraconazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Cream 5% - Variant 5', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Acyclovir Tablet 400mg - Variant 5', N'Acyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Valacyclovir 500mg - Variant 5', N'Valacyclovir', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Dapsone Gel 7.5% - Variant 5', N'Dapsone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 10mg - Variant 5', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 20mg - Variant 5', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 30mg - Variant 5', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Isotretinoin 40mg - Variant 5', N'Isotretinoin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Salicylic Acid 2% - Variant 5', N'Salicylic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 10% - Variant 5', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 20% - Variant 5', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Urea Cream 40% - Variant 5', N'Urea', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Hyaluronic Acid Serum - Variant 5', N'Hyaluronic Acid', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Niacinamide Serum 10% - Variant 5', N'Niacinamide', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Azithromycin 250mg - Variant 5', N'Azithromycin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Cefalexin 500mg - Variant 5', N'Cefalexin', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Prednisolone 5mg - Variant 5', N'Prednisolone', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Cream 0.77% - Variant 5', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Ciclopirox Shampoo 1% - Variant 5', N'Ciclopirox', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 0.75% - Variant 5', N'Metronidazole', 'available');
INSERT INTO Thuoc (TenThuoc, HoatChat, TrangThai) VALUES (N'Metronidazole Gel 1% - Variant 5', N'Metronidazole', 'available');